# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    my_user_provider.class: AppBundle\Security\Core\User\OAuthUserProvider

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: ["@doctrine"]

    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ['@doctrine', { facebook: facebookID } ]

    #my_user_provider:
      #  class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
     #   arguments: ['@fos_user.user_manager', { facebook: facebookID } , '@doctrine']
