# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    my_user_provider.class: AppBundle\Security\Core\User\OAuthUserProvider
    #id_app_facebook: 156169728227865
    #secret_id: 38375a80032be5d22e136f32b7f37c47
    graf_version: v2.8

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: ["@doctrine"]

    service_facebook_sdk:
        class: AppBundle\Services\FacebookSdk
        arguments: ["%id_app_facebook%","%secret_id%","%graf_version%"]